//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "message_recipient")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub message_id: Option<i32>,
    pub message_group_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::message::Entity",
        from = "Column::MessageId",
        to = "super::message::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Message,
    #[sea_orm(
        belongs_to = "super::message_group::Entity",
        from = "Column::MessageGroupId",
        to = "super::message_group::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MessageGroup,
}

impl Related<super::message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Message.def()
    }
}

impl Related<super::message_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MessageGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
