//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod event;
pub mod event_invitee;
pub mod message;
pub mod message_chain;
pub mod message_group;
pub mod message_recipient;
pub mod note;
pub mod organization;
pub mod organization_events;
pub mod process_events;
pub mod process_organizations;
pub mod recruitment_process;
pub mod status;
pub mod user;
pub mod user_group;
pub mod user_organizations;
pub mod user_processes;
pub mod user_statuses;
