//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::event::Entity as Event;
pub use super::event_invitee::Entity as EventInvitee;
pub use super::message::Entity as Message;
pub use super::message_chain::Entity as MessageChain;
pub use super::message_group::Entity as MessageGroup;
pub use super::message_recipient::Entity as MessageRecipient;
pub use super::note::Entity as Note;
pub use super::organization::Entity as Organization;
pub use super::organization_events::Entity as OrganizationEvents;
pub use super::process_events::Entity as ProcessEvents;
pub use super::process_organizations::Entity as ProcessOrganizations;
pub use super::recruitment_process::Entity as RecruitmentProcess;
pub use super::status::Entity as Status;
pub use super::user::Entity as User;
pub use super::user_group::Entity as UserGroup;
pub use super::user_organizations::Entity as UserOrganizations;
pub use super::user_processes::Entity as UserProcesses;
pub use super::user_statuses::Entity as UserStatuses;
