//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "process_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub process_id: i32,
    #[sea_orm(primary_key)]
    pub event_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event::Entity",
        from = "Column::EventId",
        to = "super::event::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Event,
    #[sea_orm(
        belongs_to = "super::recruitment_process::Entity",
        from = "Column::ProcessId",
        to = "super::recruitment_process::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    RecruitmentProcess,
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Event.def()
    }
}

impl Related<super::recruitment_process::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecruitmentProcess.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
